# https://circleci.com/docs/2.0/language-java/

version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    environment:
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew -PossrhUsername=blah -PossrhPassword=blah check

    post:
      - mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - find . -type f -regex ".*/build/test-results/test/*.xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
